#!/bin/bash

mapfile -t outputs < <(swaymsg -t get_outputs | jq -r '.[] | select(.active) | .name')

if [[ ${#outputs[@]} -ne 2 ]]; then
    notify-send "Cannot move workspace" "Expected two active outputs, found ${#outputs[@]}."
    exit 1
fi

read -r current_workspace current_output < <(
    swaymsg -t get_workspaces |
        jq -r '.[] | select(.focused) | [.name, .output] | @tsv'
)

for output in "${outputs[@]}"; do
    if [[ "$output" != "$current_output" ]]; then
        exec swaymsg "move workspace to output \"$output\"; workspace \"$current_workspace\""
    fi
done
