#!/bin/bash

if [[ ${ROFI_RETV:-0} == 1 && ${ROFI_INFO:-} =~ ^[0-9]+$ ]]; then
    swaymsg "[con_id=$ROFI_INFO] focus" >/dev/null
    exit
fi

swaymsg -t get_tree | jq -j '
    .. | objects |
    select(.type? == "con" and .pid? != null and .name? != null) |
    ((.app_id // .window_properties.class // "unknown") | gsub("[\\t\\n]"; " ")) +
    ": " + (.name | gsub("[\\t\\n]"; " ")) +
    "\u0000info\u001f" + (.id | tostring) + "\n"
'
